# Makefile - gccDppConsoleInet

.PHONY: all
all: \
 	gccDppConsoleInet

.PHONY: gccDppConsoleInet
gccDppConsoleInet:
	$(MAKE) -f gccDppConsoleInet.mak

.PHONY: clean
clean:
	$(MAKE) -f gccDppConsoleInet.mak clean

.PHONY: depends
depends:
	$(MAKE) -f gccDppConsoleInet.mak depends

