# Makefile - gccDppConsole

.PHONY: all
all: \
 	gccDppConsole


.PHONY: gccDppConsole
gccDppConsole:
	cd  && $(MAKE) -f gccDppConsole.mak

.PHONY: clean
clean:
	cd  && $(MAKE) -f gccDppConsole.mak clean

.PHONY: depends
depends:
	cd  && $(MAKE) -f gccDppConsole.mak depends

